version: '3.3'
services:

  carrier-pricing:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always
    depends_on: 
      - redisdb
      - mongodb


  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/var/lib/mongo
    volumes:
      - mongo-db:/var/lib/mongo
    ports:
      - 27017:27017
    expose: 
      - "27017"
    command: mongod



  redisdb:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - '6379'
    volumes:
      - redis-db:/var/lib/redis
    entrypoint: redis-server --appendonly yes
    
volumes:
  mongo-db:
  redis-db: